apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: demo
type: Opaque
data:
  USER_NAME: YWRtaW4K
  PASSWORD: VGhpc0lzQ0BtcGxpY2F0ZWQyMDIyCg==

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-loader
  namespace: demo
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
    env:
    - name: USER_NAME
      valueFrom:
        secretKeyRef:
          name: demo-secret
          key: USER_NAME
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: demo-secret
          key: PASSWORD
    volumeMounts:
    - name: secrets
      mountPath: "/secrets"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: demo-secret
      items:
      - key: USER_NAME
        path: "username"
      - key: PASSWORD
        path: "password"
