apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
  namespace: demo
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000 # optional field